// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Control.proto

package Report;

public final class Control {
  private Control() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    Report.Control.Command.CommandType getType();

    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    java.util.List<Report.Control.Command.Param> 
        getParasList();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    Report.Control.Command.Param getParas(int index);
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    int getParasCount();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    java.util.List<? extends Report.Control.Command.ParamOrBuilder> 
        getParasOrBuilderList();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    Report.Control.Command.ParamOrBuilder getParasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Report.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      type_ = 0;
      paras_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paras_ = new java.util.ArrayList<Report.Control.Command.Param>();
                mutable_bitField0_ |= 0x00000002;
              }
              paras_.add(
                  input.readMessage(Report.Control.Command.Param.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paras_ = java.util.Collections.unmodifiableList(paras_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Report.Control.internal_static_Report_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Report.Control.internal_static_Report_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.Control.Command.class, Report.Control.Command.Builder.class);
    }

    /**
     * Protobuf enum {@code Report.Command.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * up message
       * </pre>
       *
       * <code>CMT_INVALID = 0;</code>
       */
      CMT_INVALID(0),
      /**
       * <code>CMT_HSTAT = 257;</code>
       */
      CMT_HSTAT(257),
      /**
       * <code>CMT_WARNUP = 258;</code>
       */
      CMT_WARNUP(258),
      /**
       * <code>CMT_READMSG = 259;</code>
       */
      CMT_READMSG(259),
      /**
       * <pre>
       *连接充电器
       * </pre>
       *
       * <code>CMT_CONN_CHARGER = 260;</code>
       */
      CMT_CONN_CHARGER(260),
      /**
       * <pre>
       * 普通服务器下发指令的应答
       * </pre>
       *
       * <code>CMT_REP = 32768;</code>
       */
      CMT_REP(32768),
      /**
       * <pre>
       * down message
       * </pre>
       *
       * <code>CMT_LOGRT = 33024;</code>
       */
      CMT_LOGRT(33024),
      /**
       * <code>CMT_HCHECK = 33025;</code>
       */
      CMT_HCHECK(33025),
      /**
       * <pre>
       *定位指令
       * </pre>
       *
       * <code>CMT_POSP = 33040;</code>
       */
      CMT_POSP(33040),
      /**
       * <pre>
       *定位间隔
       * </pre>
       *
       * <code>CMT_POS_INTERVAL = 33041;</code>
       */
      CMT_POS_INTERVAL(33041),
      /**
       * <pre>
       *重启关机
       * </pre>
       *
       * <code>CMT_RT_OFF = 33042;</code>
       */
      CMT_RT_OFF(33042),
      /**
       * <pre>
       *终端设置服务器IP端口
       * </pre>
       *
       * <code>CMT_SERVER_SET = 33043;</code>
       */
      CMT_SERVER_SET(33043),
      /**
       * <pre>
       *终端升级
       * </pre>
       *
       * <code>CMT_UPDATE = 33044;</code>
       */
      CMT_UPDATE(33044),
      /**
       * <pre>
       *发送文字信息
       * </pre>
       *
       * <code>CMT_SENDMSG = 33045;</code>
       */
      CMT_SENDMSG(33045),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * up message
       * </pre>
       *
       * <code>CMT_INVALID = 0;</code>
       */
      public static final int CMT_INVALID_VALUE = 0;
      /**
       * <code>CMT_HSTAT = 257;</code>
       */
      public static final int CMT_HSTAT_VALUE = 257;
      /**
       * <code>CMT_WARNUP = 258;</code>
       */
      public static final int CMT_WARNUP_VALUE = 258;
      /**
       * <code>CMT_READMSG = 259;</code>
       */
      public static final int CMT_READMSG_VALUE = 259;
      /**
       * <pre>
       *连接充电器
       * </pre>
       *
       * <code>CMT_CONN_CHARGER = 260;</code>
       */
      public static final int CMT_CONN_CHARGER_VALUE = 260;
      /**
       * <pre>
       * 普通服务器下发指令的应答
       * </pre>
       *
       * <code>CMT_REP = 32768;</code>
       */
      public static final int CMT_REP_VALUE = 32768;
      /**
       * <pre>
       * down message
       * </pre>
       *
       * <code>CMT_LOGRT = 33024;</code>
       */
      public static final int CMT_LOGRT_VALUE = 33024;
      /**
       * <code>CMT_HCHECK = 33025;</code>
       */
      public static final int CMT_HCHECK_VALUE = 33025;
      /**
       * <pre>
       *定位指令
       * </pre>
       *
       * <code>CMT_POSP = 33040;</code>
       */
      public static final int CMT_POSP_VALUE = 33040;
      /**
       * <pre>
       *定位间隔
       * </pre>
       *
       * <code>CMT_POS_INTERVAL = 33041;</code>
       */
      public static final int CMT_POS_INTERVAL_VALUE = 33041;
      /**
       * <pre>
       *重启关机
       * </pre>
       *
       * <code>CMT_RT_OFF = 33042;</code>
       */
      public static final int CMT_RT_OFF_VALUE = 33042;
      /**
       * <pre>
       *终端设置服务器IP端口
       * </pre>
       *
       * <code>CMT_SERVER_SET = 33043;</code>
       */
      public static final int CMT_SERVER_SET_VALUE = 33043;
      /**
       * <pre>
       *终端升级
       * </pre>
       *
       * <code>CMT_UPDATE = 33044;</code>
       */
      public static final int CMT_UPDATE_VALUE = 33044;
      /**
       * <pre>
       *发送文字信息
       * </pre>
       *
       * <code>CMT_SENDMSG = 33045;</code>
       */
      public static final int CMT_SENDMSG_VALUE = 33045;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CommandType valueOf(int value) {
        return forNumber(value);
      }

      public static CommandType forNumber(int value) {
        switch (value) {
          case 0: return CMT_INVALID;
          case 257: return CMT_HSTAT;
          case 258: return CMT_WARNUP;
          case 259: return CMT_READMSG;
          case 260: return CMT_CONN_CHARGER;
          case 32768: return CMT_REP;
          case 33024: return CMT_LOGRT;
          case 33025: return CMT_HCHECK;
          case 33040: return CMT_POSP;
          case 33041: return CMT_POS_INTERVAL;
          case 33042: return CMT_RT_OFF;
          case 33043: return CMT_SERVER_SET;
          case 33044: return CMT_UPDATE;
          case 33045: return CMT_SENDMSG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Report.Control.Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Report.Command.CommandType)
    }

    public interface ParamOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Report.Command.Param)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      int getTypeValue();
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      Report.Control.Command.Param.ParaType getType();

      /**
       * <code>optional int64 npara = 2;</code>
       */
      long getNpara();

      /**
       * <code>optional double dpara = 3;</code>
       */
      double getDpara();

      /**
       * <code>optional string strpara = 4;</code>
       */
      java.lang.String getStrpara();
      /**
       * <code>optional string strpara = 4;</code>
       */
      com.google.protobuf.ByteString
          getStrparaBytes();

      /**
       * <code>optional bytes bpara = 5;</code>
       */
      com.google.protobuf.ByteString getBpara();
    }
    /**
     * Protobuf type {@code Report.Command.Param}
     */
    public  static final class Param extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Report.Command.Param)
        ParamOrBuilder {
      // Use Param.newBuilder() to construct.
      private Param(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Param() {
        type_ = 0;
        npara_ = 0L;
        dpara_ = 0D;
        strpara_ = "";
        bpara_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Param(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 16: {

                npara_ = input.readInt64();
                break;
              }
              case 25: {

                dpara_ = input.readDouble();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                strpara_ = s;
                break;
              }
              case 42: {

                bpara_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.Control.internal_static_Report_Command_Param_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.Control.internal_static_Report_Command_Param_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.Control.Command.Param.class, Report.Control.Command.Param.Builder.class);
      }

      /**
       * Protobuf enum {@code Report.Command.Param.ParaType}
       */
      public enum ParaType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Null = 0;</code>
         */
        Null(0),
        /**
         * <code>INT8 = 1;</code>
         */
        INT8(1),
        /**
         * <code>INT16 = 2;</code>
         */
        INT16(2),
        /**
         * <code>INT32 = 3;</code>
         */
        INT32(3),
        /**
         * <code>INT64 = 4;</code>
         */
        INT64(4),
        /**
         * <code>FLOAT = 16;</code>
         */
        FLOAT(16),
        /**
         * <code>DOUBLE = 17;</code>
         */
        DOUBLE(17),
        /**
         * <code>STRING = 32;</code>
         */
        STRING(32),
        /**
         * <code>BYTES = 33;</code>
         */
        BYTES(33),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>Null = 0;</code>
         */
        public static final int Null_VALUE = 0;
        /**
         * <code>INT8 = 1;</code>
         */
        public static final int INT8_VALUE = 1;
        /**
         * <code>INT16 = 2;</code>
         */
        public static final int INT16_VALUE = 2;
        /**
         * <code>INT32 = 3;</code>
         */
        public static final int INT32_VALUE = 3;
        /**
         * <code>INT64 = 4;</code>
         */
        public static final int INT64_VALUE = 4;
        /**
         * <code>FLOAT = 16;</code>
         */
        public static final int FLOAT_VALUE = 16;
        /**
         * <code>DOUBLE = 17;</code>
         */
        public static final int DOUBLE_VALUE = 17;
        /**
         * <code>STRING = 32;</code>
         */
        public static final int STRING_VALUE = 32;
        /**
         * <code>BYTES = 33;</code>
         */
        public static final int BYTES_VALUE = 33;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ParaType valueOf(int value) {
          return forNumber(value);
        }

        public static ParaType forNumber(int value) {
          switch (value) {
            case 0: return Null;
            case 1: return INT8;
            case 2: return INT16;
            case 3: return INT32;
            case 4: return INT64;
            case 16: return FLOAT;
            case 17: return DOUBLE;
            case 32: return STRING;
            case 33: return BYTES;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ParaType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ParaType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ParaType>() {
                public ParaType findValueByNumber(int number) {
                  return ParaType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return Report.Control.Command.Param.getDescriptor().getEnumTypes().get(0);
        }

        private static final ParaType[] VALUES = values();

        public static ParaType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private ParaType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Report.Command.Param.ParaType)
      }

      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      public Report.Control.Command.Param.ParaType getType() {
        Report.Control.Command.Param.ParaType result = Report.Control.Command.Param.ParaType.valueOf(type_);
        return result == null ? Report.Control.Command.Param.ParaType.UNRECOGNIZED : result;
      }

      public static final int NPARA_FIELD_NUMBER = 2;
      private long npara_;
      /**
       * <code>optional int64 npara = 2;</code>
       */
      public long getNpara() {
        return npara_;
      }

      public static final int DPARA_FIELD_NUMBER = 3;
      private double dpara_;
      /**
       * <code>optional double dpara = 3;</code>
       */
      public double getDpara() {
        return dpara_;
      }

      public static final int STRPARA_FIELD_NUMBER = 4;
      private volatile java.lang.Object strpara_;
      /**
       * <code>optional string strpara = 4;</code>
       */
      public java.lang.String getStrpara() {
        java.lang.Object ref = strpara_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strpara_ = s;
          return s;
        }
      }
      /**
       * <code>optional string strpara = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStrparaBytes() {
        java.lang.Object ref = strpara_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strpara_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BPARA_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString bpara_;
      /**
       * <code>optional bytes bpara = 5;</code>
       */
      public com.google.protobuf.ByteString getBpara() {
        return bpara_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (type_ != Report.Control.Command.Param.ParaType.Null.getNumber()) {
          output.writeEnum(1, type_);
        }
        if (npara_ != 0L) {
          output.writeInt64(2, npara_);
        }
        if (dpara_ != 0D) {
          output.writeDouble(3, dpara_);
        }
        if (!getStrparaBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, strpara_);
        }
        if (!bpara_.isEmpty()) {
          output.writeBytes(5, bpara_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (type_ != Report.Control.Command.Param.ParaType.Null.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (npara_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, npara_);
        }
        if (dpara_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, dpara_);
        }
        if (!getStrparaBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, strpara_);
        }
        if (!bpara_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, bpara_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Report.Control.Command.Param)) {
          return super.equals(obj);
        }
        Report.Control.Command.Param other = (Report.Control.Command.Param) obj;

        boolean result = true;
        result = result && type_ == other.type_;
        result = result && (getNpara()
            == other.getNpara());
        result = result && (
            java.lang.Double.doubleToLongBits(getDpara())
            == java.lang.Double.doubleToLongBits(
                other.getDpara()));
        result = result && getStrpara()
            .equals(other.getStrpara());
        result = result && getBpara()
            .equals(other.getBpara());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + NPARA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNpara());
        hash = (37 * hash) + DPARA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDpara()));
        hash = (37 * hash) + STRPARA_FIELD_NUMBER;
        hash = (53 * hash) + getStrpara().hashCode();
        hash = (37 * hash) + BPARA_FIELD_NUMBER;
        hash = (53 * hash) + getBpara().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Report.Control.Command.Param parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Report.Control.Command.Param parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Report.Control.Command.Param parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Report.Control.Command.Param parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Report.Control.Command.Param parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Report.Control.Command.Param parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Report.Control.Command.Param parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Report.Control.Command.Param parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Report.Control.Command.Param parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Report.Control.Command.Param parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Report.Control.Command.Param prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Report.Command.Param}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Report.Command.Param)
          Report.Control.Command.ParamOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Report.Control.internal_static_Report_Command_Param_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Report.Control.internal_static_Report_Command_Param_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Report.Control.Command.Param.class, Report.Control.Command.Param.Builder.class);
        }

        // Construct using Report.Control.Command.Param.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          type_ = 0;

          npara_ = 0L;

          dpara_ = 0D;

          strpara_ = "";

          bpara_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Report.Control.internal_static_Report_Command_Param_descriptor;
        }

        public Report.Control.Command.Param getDefaultInstanceForType() {
          return Report.Control.Command.Param.getDefaultInstance();
        }

        public Report.Control.Command.Param build() {
          Report.Control.Command.Param result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Report.Control.Command.Param buildPartial() {
          Report.Control.Command.Param result = new Report.Control.Command.Param(this);
          result.type_ = type_;
          result.npara_ = npara_;
          result.dpara_ = dpara_;
          result.strpara_ = strpara_;
          result.bpara_ = bpara_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Report.Control.Command.Param) {
            return mergeFrom((Report.Control.Command.Param)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Report.Control.Command.Param other) {
          if (other == Report.Control.Command.Param.getDefaultInstance()) return this;
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (other.getNpara() != 0L) {
            setNpara(other.getNpara());
          }
          if (other.getDpara() != 0D) {
            setDpara(other.getDpara());
          }
          if (!other.getStrpara().isEmpty()) {
            strpara_ = other.strpara_;
            onChanged();
          }
          if (other.getBpara() != com.google.protobuf.ByteString.EMPTY) {
            setBpara(other.getBpara());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Report.Control.Command.Param parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Report.Control.Command.Param) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int type_ = 0;
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Report.Control.Command.Param.ParaType getType() {
          Report.Control.Command.Param.ParaType result = Report.Control.Command.Param.ParaType.valueOf(type_);
          return result == null ? Report.Control.Command.Param.ParaType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder setType(Report.Control.Command.Param.ParaType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }

        private long npara_ ;
        /**
         * <code>optional int64 npara = 2;</code>
         */
        public long getNpara() {
          return npara_;
        }
        /**
         * <code>optional int64 npara = 2;</code>
         */
        public Builder setNpara(long value) {
          
          npara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 npara = 2;</code>
         */
        public Builder clearNpara() {
          
          npara_ = 0L;
          onChanged();
          return this;
        }

        private double dpara_ ;
        /**
         * <code>optional double dpara = 3;</code>
         */
        public double getDpara() {
          return dpara_;
        }
        /**
         * <code>optional double dpara = 3;</code>
         */
        public Builder setDpara(double value) {
          
          dpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double dpara = 3;</code>
         */
        public Builder clearDpara() {
          
          dpara_ = 0D;
          onChanged();
          return this;
        }

        private java.lang.Object strpara_ = "";
        /**
         * <code>optional string strpara = 4;</code>
         */
        public java.lang.String getStrpara() {
          java.lang.Object ref = strpara_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            strpara_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public com.google.protobuf.ByteString
            getStrparaBytes() {
          java.lang.Object ref = strpara_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            strpara_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder setStrpara(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          strpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder clearStrpara() {
          
          strpara_ = getDefaultInstance().getStrpara();
          onChanged();
          return this;
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder setStrparaBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          strpara_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString bpara_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public com.google.protobuf.ByteString getBpara() {
          return bpara_;
        }
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public Builder setBpara(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          bpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public Builder clearBpara() {
          
          bpara_ = getDefaultInstance().getBpara();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:Report.Command.Param)
      }

      // @@protoc_insertion_point(class_scope:Report.Command.Param)
      private static final Report.Control.Command.Param DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Report.Control.Command.Param();
      }

      public static Report.Control.Command.Param getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Param>
          PARSER = new com.google.protobuf.AbstractParser<Param>() {
        public Param parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Param(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Param> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Param> getParserForType() {
        return PARSER;
      }

      public Report.Control.Command.Param getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    public Report.Control.Command.CommandType getType() {
      Report.Control.Command.CommandType result = Report.Control.Command.CommandType.valueOf(type_);
      return result == null ? Report.Control.Command.CommandType.UNRECOGNIZED : result;
    }

    public static final int PARAS_FIELD_NUMBER = 2;
    private java.util.List<Report.Control.Command.Param> paras_;
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public java.util.List<Report.Control.Command.Param> getParasList() {
      return paras_;
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public java.util.List<? extends Report.Control.Command.ParamOrBuilder> 
        getParasOrBuilderList() {
      return paras_;
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public int getParasCount() {
      return paras_.size();
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public Report.Control.Command.Param getParas(int index) {
      return paras_.get(index);
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public Report.Control.Command.ParamOrBuilder getParasOrBuilder(
        int index) {
      return paras_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Report.Control.Command.CommandType.CMT_INVALID.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < paras_.size(); i++) {
        output.writeMessage(2, paras_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Report.Control.Command.CommandType.CMT_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < paras_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paras_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report.Control.Command)) {
        return super.equals(obj);
      }
      Report.Control.Command other = (Report.Control.Command) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getParasList()
          .equals(other.getParasList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getParasCount() > 0) {
        hash = (37 * hash) + PARAS_FIELD_NUMBER;
        hash = (53 * hash) + getParasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report.Control.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Control.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Control.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Control.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Control.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Control.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Control.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report.Control.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Control.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Control.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report.Control.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.Command)
        Report.Control.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.Control.internal_static_Report_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.Control.internal_static_Report_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.Control.Command.class, Report.Control.Command.Builder.class);
      }

      // Construct using Report.Control.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParasFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (parasBuilder_ == null) {
          paras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          parasBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Report.Control.internal_static_Report_Command_descriptor;
      }

      public Report.Control.Command getDefaultInstanceForType() {
        return Report.Control.Command.getDefaultInstance();
      }

      public Report.Control.Command build() {
        Report.Control.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report.Control.Command buildPartial() {
        Report.Control.Command result = new Report.Control.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (parasBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            paras_ = java.util.Collections.unmodifiableList(paras_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.paras_ = paras_;
        } else {
          result.paras_ = parasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report.Control.Command) {
          return mergeFrom((Report.Control.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report.Control.Command other) {
        if (other == Report.Control.Command.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (parasBuilder_ == null) {
          if (!other.paras_.isEmpty()) {
            if (paras_.isEmpty()) {
              paras_ = other.paras_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParasIsMutable();
              paras_.addAll(other.paras_);
            }
            onChanged();
          }
        } else {
          if (!other.paras_.isEmpty()) {
            if (parasBuilder_.isEmpty()) {
              parasBuilder_.dispose();
              parasBuilder_ = null;
              paras_ = other.paras_;
              bitField0_ = (bitField0_ & ~0x00000002);
              parasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParasFieldBuilder() : null;
            } else {
              parasBuilder_.addAllMessages(other.paras_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report.Control.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report.Control.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Report.Control.Command.CommandType getType() {
        Report.Control.Command.CommandType result = Report.Control.Command.CommandType.valueOf(type_);
        return result == null ? Report.Control.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder setType(Report.Control.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Report.Control.Command.Param> paras_ =
        java.util.Collections.emptyList();
      private void ensureParasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paras_ = new java.util.ArrayList<Report.Control.Command.Param>(paras_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Report.Control.Command.Param, Report.Control.Command.Param.Builder, Report.Control.Command.ParamOrBuilder> parasBuilder_;

      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<Report.Control.Command.Param> getParasList() {
        if (parasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paras_);
        } else {
          return parasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public int getParasCount() {
        if (parasBuilder_ == null) {
          return paras_.size();
        } else {
          return parasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.Control.Command.Param getParas(int index) {
        if (parasBuilder_ == null) {
          return paras_.get(index);
        } else {
          return parasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder setParas(
          int index, Report.Control.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.set(index, value);
          onChanged();
        } else {
          parasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder setParas(
          int index, Report.Control.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.set(index, builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(Report.Control.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.add(value);
          onChanged();
        } else {
          parasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          int index, Report.Control.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.add(index, value);
          onChanged();
        } else {
          parasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          Report.Control.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.add(builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          int index, Report.Control.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.add(index, builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addAllParas(
          java.lang.Iterable<? extends Report.Control.Command.Param> values) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, paras_);
          onChanged();
        } else {
          parasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder clearParas() {
        if (parasBuilder_ == null) {
          paras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          parasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder removeParas(int index) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.remove(index);
          onChanged();
        } else {
          parasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.Control.Command.Param.Builder getParasBuilder(
          int index) {
        return getParasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.Control.Command.ParamOrBuilder getParasOrBuilder(
          int index) {
        if (parasBuilder_ == null) {
          return paras_.get(index);  } else {
          return parasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<? extends Report.Control.Command.ParamOrBuilder> 
           getParasOrBuilderList() {
        if (parasBuilder_ != null) {
          return parasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paras_);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.Control.Command.Param.Builder addParasBuilder() {
        return getParasFieldBuilder().addBuilder(
            Report.Control.Command.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.Control.Command.Param.Builder addParasBuilder(
          int index) {
        return getParasFieldBuilder().addBuilder(
            index, Report.Control.Command.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<Report.Control.Command.Param.Builder> 
           getParasBuilderList() {
        return getParasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Report.Control.Command.Param, Report.Control.Command.Param.Builder, Report.Control.Command.ParamOrBuilder> 
          getParasFieldBuilder() {
        if (parasBuilder_ == null) {
          parasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Report.Control.Command.Param, Report.Control.Command.Param.Builder, Report.Control.Command.ParamOrBuilder>(
                  paras_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          paras_ = null;
        }
        return parasBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Report.Command)
    }

    // @@protoc_insertion_point(class_scope:Report.Command)
    private static final Report.Control.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report.Control.Command();
    }

    public static Report.Control.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public Report.Control.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.ControlProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 time_req = 1;</code>
     */
    long getTimeReq();

    /**
     * <code>optional uint32 serial_number = 2;</code>
     */
    int getSerialNumber();

    /**
     * <code>optional string tid = 3;</code>
     */
    java.lang.String getTid();
    /**
     * <code>optional string tid = 3;</code>
     */
    com.google.protobuf.ByteString
        getTidBytes();

    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    boolean hasCommand();
    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    Report.Control.Command getCommand();
    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    Report.Control.CommandOrBuilder getCommandOrBuilder();
  }
  /**
   * Protobuf type {@code Report.ControlProtocol}
   */
  public  static final class ControlProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.ControlProtocol)
      ControlProtocolOrBuilder {
    // Use ControlProtocol.newBuilder() to construct.
    private ControlProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlProtocol() {
      timeReq_ = 0L;
      serialNumber_ = 0;
      tid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ControlProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timeReq_ = input.readInt64();
              break;
            }
            case 16: {

              serialNumber_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tid_ = s;
              break;
            }
            case 34: {
              Report.Control.Command.Builder subBuilder = null;
              if (command_ != null) {
                subBuilder = command_.toBuilder();
              }
              command_ = input.readMessage(Report.Control.Command.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(command_);
                command_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Report.Control.internal_static_Report_ControlProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Report.Control.internal_static_Report_ControlProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.Control.ControlProtocol.class, Report.Control.ControlProtocol.Builder.class);
    }

    public static final int TIME_REQ_FIELD_NUMBER = 1;
    private long timeReq_;
    /**
     * <code>optional int64 time_req = 1;</code>
     */
    public long getTimeReq() {
      return timeReq_;
    }

    public static final int SERIAL_NUMBER_FIELD_NUMBER = 2;
    private int serialNumber_;
    /**
     * <code>optional uint32 serial_number = 2;</code>
     */
    public int getSerialNumber() {
      return serialNumber_;
    }

    public static final int TID_FIELD_NUMBER = 3;
    private volatile java.lang.Object tid_;
    /**
     * <code>optional string tid = 3;</code>
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string tid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 4;
    private Report.Control.Command command_;
    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    public boolean hasCommand() {
      return command_ != null;
    }
    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    public Report.Control.Command getCommand() {
      return command_ == null ? Report.Control.Command.getDefaultInstance() : command_;
    }
    /**
     * <code>optional .Report.Command command = 4;</code>
     */
    public Report.Control.CommandOrBuilder getCommandOrBuilder() {
      return getCommand();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeReq_ != 0L) {
        output.writeInt64(1, timeReq_);
      }
      if (serialNumber_ != 0) {
        output.writeUInt32(2, serialNumber_);
      }
      if (!getTidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tid_);
      }
      if (command_ != null) {
        output.writeMessage(4, getCommand());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeReq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeReq_);
      }
      if (serialNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, serialNumber_);
      }
      if (!getTidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tid_);
      }
      if (command_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCommand());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report.Control.ControlProtocol)) {
        return super.equals(obj);
      }
      Report.Control.ControlProtocol other = (Report.Control.ControlProtocol) obj;

      boolean result = true;
      result = result && (getTimeReq()
          == other.getTimeReq());
      result = result && (getSerialNumber()
          == other.getSerialNumber());
      result = result && getTid()
          .equals(other.getTid());
      result = result && (hasCommand() == other.hasCommand());
      if (hasCommand()) {
        result = result && getCommand()
            .equals(other.getCommand());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_REQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeReq());
      hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNumber();
      hash = (37 * hash) + TID_FIELD_NUMBER;
      hash = (53 * hash) + getTid().hashCode();
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report.Control.ControlProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Control.ControlProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Control.ControlProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Control.ControlProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Control.ControlProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Control.ControlProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Control.ControlProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report.Control.ControlProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Control.ControlProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Control.ControlProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report.Control.ControlProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.ControlProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.ControlProtocol)
        Report.Control.ControlProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.Control.internal_static_Report_ControlProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.Control.internal_static_Report_ControlProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.Control.ControlProtocol.class, Report.Control.ControlProtocol.Builder.class);
      }

      // Construct using Report.Control.ControlProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timeReq_ = 0L;

        serialNumber_ = 0;

        tid_ = "";

        if (commandBuilder_ == null) {
          command_ = null;
        } else {
          command_ = null;
          commandBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Report.Control.internal_static_Report_ControlProtocol_descriptor;
      }

      public Report.Control.ControlProtocol getDefaultInstanceForType() {
        return Report.Control.ControlProtocol.getDefaultInstance();
      }

      public Report.Control.ControlProtocol build() {
        Report.Control.ControlProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report.Control.ControlProtocol buildPartial() {
        Report.Control.ControlProtocol result = new Report.Control.ControlProtocol(this);
        result.timeReq_ = timeReq_;
        result.serialNumber_ = serialNumber_;
        result.tid_ = tid_;
        if (commandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = commandBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report.Control.ControlProtocol) {
          return mergeFrom((Report.Control.ControlProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report.Control.ControlProtocol other) {
        if (other == Report.Control.ControlProtocol.getDefaultInstance()) return this;
        if (other.getTimeReq() != 0L) {
          setTimeReq(other.getTimeReq());
        }
        if (other.getSerialNumber() != 0) {
          setSerialNumber(other.getSerialNumber());
        }
        if (!other.getTid().isEmpty()) {
          tid_ = other.tid_;
          onChanged();
        }
        if (other.hasCommand()) {
          mergeCommand(other.getCommand());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report.Control.ControlProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report.Control.ControlProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timeReq_ ;
      /**
       * <code>optional int64 time_req = 1;</code>
       */
      public long getTimeReq() {
        return timeReq_;
      }
      /**
       * <code>optional int64 time_req = 1;</code>
       */
      public Builder setTimeReq(long value) {
        
        timeReq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time_req = 1;</code>
       */
      public Builder clearTimeReq() {
        
        timeReq_ = 0L;
        onChanged();
        return this;
      }

      private int serialNumber_ ;
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public int getSerialNumber() {
        return serialNumber_;
      }
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public Builder setSerialNumber(int value) {
        
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public Builder clearSerialNumber() {
        
        serialNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tid_ = "";
      /**
       * <code>optional string tid = 3;</code>
       */
      public java.lang.String getTid() {
        java.lang.Object ref = tid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTidBytes() {
        java.lang.Object ref = tid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tid = 3;</code>
       */
      public Builder setTid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tid = 3;</code>
       */
      public Builder clearTid() {
        
        tid_ = getDefaultInstance().getTid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tid = 3;</code>
       */
      public Builder setTidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tid_ = value;
        onChanged();
        return this;
      }

      private Report.Control.Command command_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Report.Control.Command, Report.Control.Command.Builder, Report.Control.CommandOrBuilder> commandBuilder_;
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public boolean hasCommand() {
        return commandBuilder_ != null || command_ != null;
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Report.Control.Command getCommand() {
        if (commandBuilder_ == null) {
          return command_ == null ? Report.Control.Command.getDefaultInstance() : command_;
        } else {
          return commandBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Builder setCommand(Report.Control.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          commandBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Builder setCommand(
          Report.Control.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Builder mergeCommand(Report.Control.Command value) {
        if (commandBuilder_ == null) {
          if (command_ != null) {
            command_ =
              Report.Control.Command.newBuilder(command_).mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          commandBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          command_ = null;
          onChanged();
        } else {
          command_ = null;
          commandBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Report.Control.Command.Builder getCommandBuilder() {
        
        onChanged();
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      public Report.Control.CommandOrBuilder getCommandOrBuilder() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          return command_ == null ?
              Report.Control.Command.getDefaultInstance() : command_;
        }
      }
      /**
       * <code>optional .Report.Command command = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Report.Control.Command, Report.Control.Command.Builder, Report.Control.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Report.Control.Command, Report.Control.Command.Builder, Report.Control.CommandOrBuilder>(
                  getCommand(),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Report.ControlProtocol)
    }

    // @@protoc_insertion_point(class_scope:Report.ControlProtocol)
    private static final Report.Control.ControlProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report.Control.ControlProtocol();
    }

    public static Report.Control.ControlProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlProtocol>
        PARSER = new com.google.protobuf.AbstractParser<ControlProtocol>() {
      public ControlProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ControlProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlProtocol> getParserForType() {
      return PARSER;
    }

    public Report.Control.ControlProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_Command_Param_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_Command_Param_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_ControlProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_ControlProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rControl.proto\022\006Report\"\321\004\n\007Command\022)\n\004t" +
      "ype\030\001 \001(\0162\033.Report.Command.CommandType\022$" +
      "\n\005paras\030\002 \003(\0132\025.Report.Command.Param\032\342\001\n" +
      "\005Param\022,\n\004type\030\001 \001(\0162\036.Report.Command.Pa" +
      "ram.ParaType\022\r\n\005npara\030\002 \001(\003\022\r\n\005dpara\030\003 \001" +
      "(\001\022\017\n\007strpara\030\004 \001(\t\022\r\n\005bpara\030\005 \001(\014\"m\n\010Pa" +
      "raType\022\010\n\004Null\020\000\022\010\n\004INT8\020\001\022\t\n\005INT16\020\002\022\t\n" +
      "\005INT32\020\003\022\t\n\005INT64\020\004\022\t\n\005FLOAT\020\020\022\n\n\006DOUBLE" +
      "\020\021\022\n\n\006STRING\020 \022\t\n\005BYTES\020!\"\217\002\n\013CommandTyp" +
      "e\022\017\n\013CMT_INVALID\020\000\022\016\n\tCMT_HSTAT\020\201\002\022\017\n\nCM",
      "T_WARNUP\020\202\002\022\020\n\013CMT_READMSG\020\203\002\022\025\n\020CMT_CON" +
      "N_CHARGER\020\204\002\022\r\n\007CMT_REP\020\200\200\002\022\017\n\tCMT_LOGRT" +
      "\020\200\202\002\022\020\n\nCMT_HCHECK\020\201\202\002\022\016\n\010CMT_POSP\020\220\202\002\022\026" +
      "\n\020CMT_POS_INTERVAL\020\221\202\002\022\020\n\nCMT_RT_OFF\020\222\202\002" +
      "\022\024\n\016CMT_SERVER_SET\020\223\202\002\022\020\n\nCMT_UPDATE\020\224\202\002" +
      "\022\021\n\013CMT_SENDMSG\020\225\202\002\"i\n\017ControlProtocol\022\020" +
      "\n\010time_req\030\001 \001(\003\022\025\n\rserial_number\030\002 \001(\r\022" +
      "\013\n\003tid\030\003 \001(\t\022 \n\007command\030\004 \001(\0132\017.Report.C" +
      "ommandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Report_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Report_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_Command_descriptor,
        new java.lang.String[] { "Type", "Paras", });
    internal_static_Report_Command_Param_descriptor =
      internal_static_Report_Command_descriptor.getNestedTypes().get(0);
    internal_static_Report_Command_Param_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_Command_Param_descriptor,
        new java.lang.String[] { "Type", "Npara", "Dpara", "Strpara", "Bpara", });
    internal_static_Report_ControlProtocol_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Report_ControlProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_ControlProtocol_descriptor,
        new java.lang.String[] { "TimeReq", "SerialNumber", "Tid", "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
