// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Manage.proto

package Report;

public final class Manage {
  private Manage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ManageProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.ManageProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求时间
     * </pre>
     *
     * <code>optional string time_req = 1;</code>
     */
    java.lang.String getTimeReq();
    /**
     * <pre>
     * 请求时间
     * </pre>
     *
     * <code>optional string time_req = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimeReqBytes();

    /**
     * <pre>
     * 流水号
     * </pre>
     *
     * <code>optional string serial_number = 2;</code>
     */
    java.lang.String getSerialNumber();
    /**
     * <pre>
     * 流水号
     * </pre>
     *
     * <code>optional string serial_number = 2;</code>
     */
    com.google.protobuf.ByteString
        getSerialNumberBytes();

    /**
     * <pre>
     * 终端标识
     * </pre>
     *
     * <code>optional string tid = 3;</code>
     */
    java.lang.String getTid();
    /**
     * <pre>
     * 终端标识
     * </pre>
     *
     * <code>optional string tid = 3;</code>
     */
    com.google.protobuf.ByteString
        getTidBytes();

    /**
     * <pre>
     * 终端管理类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 终端管理类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
     */
    Report.Manage.ManageProtocol.ManageType getType();

    /**
     * <pre>
     * 应答结果类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
     */
    int getResultValue();
    /**
     * <pre>
     * 应答结果类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
     */
    Report.Manage.ManageProtocol.ResultType getResult();

    /**
     * <pre>
     * 终端类型(默认watch）
     * </pre>
     *
     * <code>optional string terminalType = 6;</code>
     */
    java.lang.String getTerminalType();
    /**
     * <pre>
     * 终端类型(默认watch）
     * </pre>
     *
     * <code>optional string terminalType = 6;</code>
     */
    com.google.protobuf.ByteString
        getTerminalTypeBytes();

    /**
     * <pre>
     * 协议类型(默认xixun)
     * </pre>
     *
     * <code>optional string protocolType = 7;</code>
     */
    java.lang.String getProtocolType();
    /**
     * <pre>
     * 协议类型(默认xixun)
     * </pre>
     *
     * <code>optional string protocolType = 7;</code>
     */
    com.google.protobuf.ByteString
        getProtocolTypeBytes();

    /**
     * <pre>
     * 自己的独特参数
     * </pre>
     *
     * <code>optional string myParam = 8;</code>
     */
    java.lang.String getMyParam();
    /**
     * <pre>
     * 自己的独特参数
     * </pre>
     *
     * <code>optional string myParam = 8;</code>
     */
    com.google.protobuf.ByteString
        getMyParamBytes();
  }
  /**
   * Protobuf type {@code Report.ManageProtocol}
   */
  public  static final class ManageProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.ManageProtocol)
      ManageProtocolOrBuilder {
    // Use ManageProtocol.newBuilder() to construct.
    private ManageProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ManageProtocol() {
      timeReq_ = "";
      serialNumber_ = "";
      tid_ = "";
      type_ = 0;
      result_ = 0;
      terminalType_ = "";
      protocolType_ = "";
      myParam_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ManageProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              timeReq_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serialNumber_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tid_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              terminalType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              protocolType_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              myParam_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Report.Manage.internal_static_Report_ManageProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Report.Manage.internal_static_Report_ManageProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.Manage.ManageProtocol.class, Report.Manage.ManageProtocol.Builder.class);
    }

    /**
     * Protobuf enum {@code Report.ManageProtocol.ManageType}
     */
    public enum ManageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 注册
       * </pre>
       *
       * <code>REG = 0;</code>
       */
      REG(0),
      /**
       * <pre>
       * 登录（鉴权）
       * </pre>
       *
       * <code>LOGIN = 1;</code>
       */
      LOGIN(1),
      /**
       * <pre>
       * 退出
       * </pre>
       *
       * <code>LOGOUT = 2;</code>
       */
      LOGOUT(2),
      /**
       * <pre>
       * 注销
       * </pre>
       *
       * <code>CANCEL = 3;</code>
       */
      CANCEL(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 注册
       * </pre>
       *
       * <code>REG = 0;</code>
       */
      public static final int REG_VALUE = 0;
      /**
       * <pre>
       * 登录（鉴权）
       * </pre>
       *
       * <code>LOGIN = 1;</code>
       */
      public static final int LOGIN_VALUE = 1;
      /**
       * <pre>
       * 退出
       * </pre>
       *
       * <code>LOGOUT = 2;</code>
       */
      public static final int LOGOUT_VALUE = 2;
      /**
       * <pre>
       * 注销
       * </pre>
       *
       * <code>CANCEL = 3;</code>
       */
      public static final int CANCEL_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ManageType valueOf(int value) {
        return forNumber(value);
      }

      public static ManageType forNumber(int value) {
        switch (value) {
          case 0: return REG;
          case 1: return LOGIN;
          case 2: return LOGOUT;
          case 3: return CANCEL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ManageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ManageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ManageType>() {
              public ManageType findValueByNumber(int number) {
                return ManageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Report.Manage.ManageProtocol.getDescriptor().getEnumTypes().get(0);
      }

      private static final ManageType[] VALUES = values();

      public static ManageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ManageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Report.ManageProtocol.ManageType)
    }

    /**
     * Protobuf enum {@code Report.ManageProtocol.ResultType}
     */
    public enum ResultType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 成功
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <pre>
       * 欠费
       * </pre>
       *
       * <code>ARREARAGE = 1;</code>
       */
      ARREARAGE(1),
      /**
       * <pre>
       * 非法用户
       * </pre>
       *
       * <code>INVALID = 2;</code>
       */
      INVALID(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 成功
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <pre>
       * 欠费
       * </pre>
       *
       * <code>ARREARAGE = 1;</code>
       */
      public static final int ARREARAGE_VALUE = 1;
      /**
       * <pre>
       * 非法用户
       * </pre>
       *
       * <code>INVALID = 2;</code>
       */
      public static final int INVALID_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResultType valueOf(int value) {
        return forNumber(value);
      }

      public static ResultType forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return ARREARAGE;
          case 2: return INVALID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResultType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultType>() {
              public ResultType findValueByNumber(int number) {
                return ResultType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Report.Manage.ManageProtocol.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResultType[] VALUES = values();

      public static ResultType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResultType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Report.ManageProtocol.ResultType)
    }

    public static final int TIME_REQ_FIELD_NUMBER = 1;
    private volatile java.lang.Object timeReq_;
    /**
     * <pre>
     * 请求时间
     * </pre>
     *
     * <code>optional string time_req = 1;</code>
     */
    public java.lang.String getTimeReq() {
      java.lang.Object ref = timeReq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeReq_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求时间
     * </pre>
     *
     * <code>optional string time_req = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeReqBytes() {
      java.lang.Object ref = timeReq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeReq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERIAL_NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object serialNumber_;
    /**
     * <pre>
     * 流水号
     * </pre>
     *
     * <code>optional string serial_number = 2;</code>
     */
    public java.lang.String getSerialNumber() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serialNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 流水号
     * </pre>
     *
     * <code>optional string serial_number = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TID_FIELD_NUMBER = 3;
    private volatile java.lang.Object tid_;
    /**
     * <pre>
     * 终端标识
     * </pre>
     *
     * <code>optional string tid = 3;</code>
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 终端标识
     * </pre>
     *
     * <code>optional string tid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 终端管理类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 终端管理类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
     */
    public Report.Manage.ManageProtocol.ManageType getType() {
      Report.Manage.ManageProtocol.ManageType result = Report.Manage.ManageProtocol.ManageType.valueOf(type_);
      return result == null ? Report.Manage.ManageProtocol.ManageType.UNRECOGNIZED : result;
    }

    public static final int RESULT_FIELD_NUMBER = 5;
    private int result_;
    /**
     * <pre>
     * 应答结果类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <pre>
     * 应答结果类型
     * </pre>
     *
     * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
     */
    public Report.Manage.ManageProtocol.ResultType getResult() {
      Report.Manage.ManageProtocol.ResultType result = Report.Manage.ManageProtocol.ResultType.valueOf(result_);
      return result == null ? Report.Manage.ManageProtocol.ResultType.UNRECOGNIZED : result;
    }

    public static final int TERMINALTYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object terminalType_;
    /**
     * <pre>
     * 终端类型(默认watch）
     * </pre>
     *
     * <code>optional string terminalType = 6;</code>
     */
    public java.lang.String getTerminalType() {
      java.lang.Object ref = terminalType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        terminalType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 终端类型(默认watch）
     * </pre>
     *
     * <code>optional string terminalType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalTypeBytes() {
      java.lang.Object ref = terminalType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        terminalType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOLTYPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object protocolType_;
    /**
     * <pre>
     * 协议类型(默认xixun)
     * </pre>
     *
     * <code>optional string protocolType = 7;</code>
     */
    public java.lang.String getProtocolType() {
      java.lang.Object ref = protocolType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocolType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 协议类型(默认xixun)
     * </pre>
     *
     * <code>optional string protocolType = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolTypeBytes() {
      java.lang.Object ref = protocolType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocolType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MYPARAM_FIELD_NUMBER = 8;
    private volatile java.lang.Object myParam_;
    /**
     * <pre>
     * 自己的独特参数
     * </pre>
     *
     * <code>optional string myParam = 8;</code>
     */
    public java.lang.String getMyParam() {
      java.lang.Object ref = myParam_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        myParam_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 自己的独特参数
     * </pre>
     *
     * <code>optional string myParam = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMyParamBytes() {
      java.lang.Object ref = myParam_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimeReqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeReq_);
      }
      if (!getSerialNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serialNumber_);
      }
      if (!getTidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tid_);
      }
      if (type_ != Report.Manage.ManageProtocol.ManageType.REG.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (result_ != Report.Manage.ManageProtocol.ResultType.SUCCESS.getNumber()) {
        output.writeEnum(5, result_);
      }
      if (!getTerminalTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, terminalType_);
      }
      if (!getProtocolTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, protocolType_);
      }
      if (!getMyParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, myParam_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimeReqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeReq_);
      }
      if (!getSerialNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serialNumber_);
      }
      if (!getTidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tid_);
      }
      if (type_ != Report.Manage.ManageProtocol.ManageType.REG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (result_ != Report.Manage.ManageProtocol.ResultType.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, result_);
      }
      if (!getTerminalTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, terminalType_);
      }
      if (!getProtocolTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, protocolType_);
      }
      if (!getMyParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, myParam_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report.Manage.ManageProtocol)) {
        return super.equals(obj);
      }
      Report.Manage.ManageProtocol other = (Report.Manage.ManageProtocol) obj;

      boolean result = true;
      result = result && getTimeReq()
          .equals(other.getTimeReq());
      result = result && getSerialNumber()
          .equals(other.getSerialNumber());
      result = result && getTid()
          .equals(other.getTid());
      result = result && type_ == other.type_;
      result = result && result_ == other.result_;
      result = result && getTerminalType()
          .equals(other.getTerminalType());
      result = result && getProtocolType()
          .equals(other.getProtocolType());
      result = result && getMyParam()
          .equals(other.getMyParam());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_REQ_FIELD_NUMBER;
      hash = (53 * hash) + getTimeReq().hashCode();
      hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNumber().hashCode();
      hash = (37 * hash) + TID_FIELD_NUMBER;
      hash = (53 * hash) + getTid().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + TERMINALTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalType().hashCode();
      hash = (37 * hash) + PROTOCOLTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProtocolType().hashCode();
      hash = (37 * hash) + MYPARAM_FIELD_NUMBER;
      hash = (53 * hash) + getMyParam().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report.Manage.ManageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Manage.ManageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Manage.ManageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.Manage.ManageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.Manage.ManageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Manage.ManageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Manage.ManageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report.Manage.ManageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.Manage.ManageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.Manage.ManageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report.Manage.ManageProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.ManageProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.ManageProtocol)
        Report.Manage.ManageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.Manage.internal_static_Report_ManageProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.Manage.internal_static_Report_ManageProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.Manage.ManageProtocol.class, Report.Manage.ManageProtocol.Builder.class);
      }

      // Construct using Report.Manage.ManageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timeReq_ = "";

        serialNumber_ = "";

        tid_ = "";

        type_ = 0;

        result_ = 0;

        terminalType_ = "";

        protocolType_ = "";

        myParam_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Report.Manage.internal_static_Report_ManageProtocol_descriptor;
      }

      public Report.Manage.ManageProtocol getDefaultInstanceForType() {
        return Report.Manage.ManageProtocol.getDefaultInstance();
      }

      public Report.Manage.ManageProtocol build() {
        Report.Manage.ManageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report.Manage.ManageProtocol buildPartial() {
        Report.Manage.ManageProtocol result = new Report.Manage.ManageProtocol(this);
        result.timeReq_ = timeReq_;
        result.serialNumber_ = serialNumber_;
        result.tid_ = tid_;
        result.type_ = type_;
        result.result_ = result_;
        result.terminalType_ = terminalType_;
        result.protocolType_ = protocolType_;
        result.myParam_ = myParam_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report.Manage.ManageProtocol) {
          return mergeFrom((Report.Manage.ManageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report.Manage.ManageProtocol other) {
        if (other == Report.Manage.ManageProtocol.getDefaultInstance()) return this;
        if (!other.getTimeReq().isEmpty()) {
          timeReq_ = other.timeReq_;
          onChanged();
        }
        if (!other.getSerialNumber().isEmpty()) {
          serialNumber_ = other.serialNumber_;
          onChanged();
        }
        if (!other.getTid().isEmpty()) {
          tid_ = other.tid_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.getTerminalType().isEmpty()) {
          terminalType_ = other.terminalType_;
          onChanged();
        }
        if (!other.getProtocolType().isEmpty()) {
          protocolType_ = other.protocolType_;
          onChanged();
        }
        if (!other.getMyParam().isEmpty()) {
          myParam_ = other.myParam_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report.Manage.ManageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report.Manage.ManageProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object timeReq_ = "";
      /**
       * <pre>
       * 请求时间
       * </pre>
       *
       * <code>optional string time_req = 1;</code>
       */
      public java.lang.String getTimeReq() {
        java.lang.Object ref = timeReq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeReq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求时间
       * </pre>
       *
       * <code>optional string time_req = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimeReqBytes() {
        java.lang.Object ref = timeReq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeReq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求时间
       * </pre>
       *
       * <code>optional string time_req = 1;</code>
       */
      public Builder setTimeReq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeReq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求时间
       * </pre>
       *
       * <code>optional string time_req = 1;</code>
       */
      public Builder clearTimeReq() {
        
        timeReq_ = getDefaultInstance().getTimeReq();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求时间
       * </pre>
       *
       * <code>optional string time_req = 1;</code>
       */
      public Builder setTimeReqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeReq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serialNumber_ = "";
      /**
       * <pre>
       * 流水号
       * </pre>
       *
       * <code>optional string serial_number = 2;</code>
       */
      public java.lang.String getSerialNumber() {
        java.lang.Object ref = serialNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serialNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 流水号
       * </pre>
       *
       * <code>optional string serial_number = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNumberBytes() {
        java.lang.Object ref = serialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 流水号
       * </pre>
       *
       * <code>optional string serial_number = 2;</code>
       */
      public Builder setSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 流水号
       * </pre>
       *
       * <code>optional string serial_number = 2;</code>
       */
      public Builder clearSerialNumber() {
        
        serialNumber_ = getDefaultInstance().getSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 流水号
       * </pre>
       *
       * <code>optional string serial_number = 2;</code>
       */
      public Builder setSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serialNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tid_ = "";
      /**
       * <pre>
       * 终端标识
       * </pre>
       *
       * <code>optional string tid = 3;</code>
       */
      public java.lang.String getTid() {
        java.lang.Object ref = tid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 终端标识
       * </pre>
       *
       * <code>optional string tid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTidBytes() {
        java.lang.Object ref = tid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 终端标识
       * </pre>
       *
       * <code>optional string tid = 3;</code>
       */
      public Builder setTid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端标识
       * </pre>
       *
       * <code>optional string tid = 3;</code>
       */
      public Builder clearTid() {
        
        tid_ = getDefaultInstance().getTid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端标识
       * </pre>
       *
       * <code>optional string tid = 3;</code>
       */
      public Builder setTidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tid_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 终端管理类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 终端管理类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端管理类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
       */
      public Report.Manage.ManageProtocol.ManageType getType() {
        Report.Manage.ManageProtocol.ManageType result = Report.Manage.ManageProtocol.ManageType.valueOf(type_);
        return result == null ? Report.Manage.ManageProtocol.ManageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 终端管理类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
       */
      public Builder setType(Report.Manage.ManageProtocol.ManageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端管理类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ManageType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int result_ = 0;
      /**
       * <pre>
       * 应答结果类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <pre>
       * 应答结果类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应答结果类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
       */
      public Report.Manage.ManageProtocol.ResultType getResult() {
        Report.Manage.ManageProtocol.ResultType result = Report.Manage.ManageProtocol.ResultType.valueOf(result_);
        return result == null ? Report.Manage.ManageProtocol.ResultType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 应答结果类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
       */
      public Builder setResult(Report.Manage.ManageProtocol.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应答结果类型
       * </pre>
       *
       * <code>optional .Report.ManageProtocol.ResultType result = 5;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object terminalType_ = "";
      /**
       * <pre>
       * 终端类型(默认watch）
       * </pre>
       *
       * <code>optional string terminalType = 6;</code>
       */
      public java.lang.String getTerminalType() {
        java.lang.Object ref = terminalType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          terminalType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 终端类型(默认watch）
       * </pre>
       *
       * <code>optional string terminalType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTerminalTypeBytes() {
        java.lang.Object ref = terminalType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          terminalType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 终端类型(默认watch）
       * </pre>
       *
       * <code>optional string terminalType = 6;</code>
       */
      public Builder setTerminalType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        terminalType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端类型(默认watch）
       * </pre>
       *
       * <code>optional string terminalType = 6;</code>
       */
      public Builder clearTerminalType() {
        
        terminalType_ = getDefaultInstance().getTerminalType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 终端类型(默认watch）
       * </pre>
       *
       * <code>optional string terminalType = 6;</code>
       */
      public Builder setTerminalTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        terminalType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object protocolType_ = "";
      /**
       * <pre>
       * 协议类型(默认xixun)
       * </pre>
       *
       * <code>optional string protocolType = 7;</code>
       */
      public java.lang.String getProtocolType() {
        java.lang.Object ref = protocolType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          protocolType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 协议类型(默认xixun)
       * </pre>
       *
       * <code>optional string protocolType = 7;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolTypeBytes() {
        java.lang.Object ref = protocolType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protocolType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 协议类型(默认xixun)
       * </pre>
       *
       * <code>optional string protocolType = 7;</code>
       */
      public Builder setProtocolType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protocolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议类型(默认xixun)
       * </pre>
       *
       * <code>optional string protocolType = 7;</code>
       */
      public Builder clearProtocolType() {
        
        protocolType_ = getDefaultInstance().getProtocolType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议类型(默认xixun)
       * </pre>
       *
       * <code>optional string protocolType = 7;</code>
       */
      public Builder setProtocolTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protocolType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object myParam_ = "";
      /**
       * <pre>
       * 自己的独特参数
       * </pre>
       *
       * <code>optional string myParam = 8;</code>
       */
      public java.lang.String getMyParam() {
        java.lang.Object ref = myParam_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          myParam_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 自己的独特参数
       * </pre>
       *
       * <code>optional string myParam = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMyParamBytes() {
        java.lang.Object ref = myParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 自己的独特参数
       * </pre>
       *
       * <code>optional string myParam = 8;</code>
       */
      public Builder setMyParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        myParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 自己的独特参数
       * </pre>
       *
       * <code>optional string myParam = 8;</code>
       */
      public Builder clearMyParam() {
        
        myParam_ = getDefaultInstance().getMyParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 自己的独特参数
       * </pre>
       *
       * <code>optional string myParam = 8;</code>
       */
      public Builder setMyParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        myParam_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Report.ManageProtocol)
    }

    // @@protoc_insertion_point(class_scope:Report.ManageProtocol)
    private static final Report.Manage.ManageProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report.Manage.ManageProtocol();
    }

    public static Report.Manage.ManageProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ManageProtocol>
        PARSER = new com.google.protobuf.AbstractParser<ManageProtocol>() {
      public ManageProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ManageProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ManageProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ManageProtocol> getParserForType() {
      return PARSER;
    }

    public Report.Manage.ManageProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_ManageProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_ManageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Manage.proto\022\006Report\"\330\002\n\016ManageProtoco" +
      "l\022\020\n\010time_req\030\001 \001(\t\022\025\n\rserial_number\030\002 \001" +
      "(\t\022\013\n\003tid\030\003 \001(\t\022/\n\004type\030\004 \001(\0162!.Report.M" +
      "anageProtocol.ManageType\0221\n\006result\030\005 \001(\016" +
      "2!.Report.ManageProtocol.ResultType\022\024\n\014t" +
      "erminalType\030\006 \001(\t\022\024\n\014protocolType\030\007 \001(\t\022" +
      "\017\n\007myParam\030\010 \001(\t\"8\n\nManageType\022\007\n\003REG\020\000\022" +
      "\t\n\005LOGIN\020\001\022\n\n\006LOGOUT\020\002\022\n\n\006CANCEL\020\003\"5\n\nRe" +
      "sultType\022\013\n\007SUCCESS\020\000\022\r\n\tARREARAGE\020\001\022\013\n\007" +
      "INVALID\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Report_ManageProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Report_ManageProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_ManageProtocol_descriptor,
        new java.lang.String[] { "TimeReq", "SerialNumber", "Tid", "Type", "Result", "TerminalType", "ProtocolType", "MyParam", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
